name: Black

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Check code with black
      run: touch .env && docker-compose run black
